[package]
edition.workspace = true
license.workspace = true
name = "jsonnet-cli"
publish.workspace = true
version.workspace = true

[lints]
workspace = true

[[bin]]
doctest = false
name = "jsonnet-cli"
test = false

[dependencies]
diagnostic.workspace = true
env_logger.workspace = true
paths.workspace = true
pico-args.workspace = true

jsonnet-analyze.path = "../jsonnet-analyze"
lang-srv-state.path = "../lang-srv-state"
